# Generated by Django 4.0.1 on 2022-02-04 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
