# Generated by Django 4.0.1 on 2022-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_friend_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='account_type',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Basic'), ('E', 'Every')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
