# Generated by Django 4.0.1 on 2022-02-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_schooladmin_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='account_type',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Basic'), ('E', 'Every')], default='F', max_length=1),
        ),
    ]
