# Generated by Django 4.0.1 on 2022-02-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_alter_lecture_time_list'),
        ('notifications', '0002_alter_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.lecture'),
        ),
    ]
