# Generated by Django 4.0.1 on 2022-02-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FR', 'Friend'), ('FQ', 'Friend Request'), ('LE', 'Lecture'), ('HC', 'Homework Create'), ('HU', 'Homework Update'), ('HS', 'Homework Submission'), ('AR', 'Article')], max_length=2),
        ),
    ]
