# Generated by Django 4.0.1 on 2022-02-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
