# Generated by Django 4.0.1 on 2022-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time_list',
            field=models.JSONField(),
        ),
    ]
