# Generated by Django 4.0.1 on 2022-01-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_homework_alter_lecture_student_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_list', to='schools.lecture'),
        ),
    ]
