# Generated by Django 4.0.1 on 2022-01-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_homework_writer_name_alter_homework_writer_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(default='', max_length=10, null=True),
            preserve_default=False,
        ),
    ]
