# Generated by Django 4.0.1 on 2022-02-05 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0007_alter_school_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='writer_name',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='writer_pk',
        ),
        migrations.AddField(
            model_name='homework',
            name='writed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homework_list', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=False,
        ),
    ]
