# Generated by Django 4.0.1 on 2022-02-05 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0008_remove_homework_writer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='writed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
