# Generated by Django 4.0.1 on 2022-02-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_alter_homework_writed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='writed',
            new_name='writer',
        ),
    ]
