# Generated by Django 4.0.1 on 2022-02-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_rename_writed_homework_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_list', to='schools.lecture'),
        ),
    ]
