# Generated by Django 4.0.1 on 2022-02-05 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0011_alter_homework_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('creted_ad', models.DateTimeField(auto_now_add=True)),
                # ('file', models.FileField(blank=True, upload_to=schools.models.HomeworkSubmission.homework_submission_path)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='schools.homework')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submission_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
