# Generated by Django 4.0.1 on 2022-02-05 19:41

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_homeworksubmission'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='homeworksubmission',
    #         name='file',
    #         field=models.FileField(blank=True, null=True, upload_to=schools.models.HomeworkSubmission.homework_submission_path),
    #     ),
    # ]
