# Generated by Django 4.0.1 on 2022-02-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_homeworksubmission_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworksubmission',
            old_name='creted_ad',
            new_name='creted_at',
        ),
    ]
