# Generated by Django 4.0.1 on 2022-02-06 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0014_rename_creted_ad_homeworksubmission_creted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_list', to='schools.lecture')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
