# Generated by Django 4.0.1 on 2022-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
