# Generated by Django 4.0.1 on 2022-02-14 11:25

from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_alter_lecture_time_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmissionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=schools.models.HomeworkSubmissionFiles.homework_submission_path)),
                ('homework_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submission_files', to='schools.homeworksubmission')),
            ],
        ),
    ]
