# Generated by Django 4.0.1 on 2022-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_body_quiz_content_alter_quiz_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
