# Generated by Django 4.0.1 on 2022-02-15 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_rename_content_quiz_body_alter_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_list', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
